name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
#RUST_VERSION
      RUST_VERSION: 1.90.0
#RUST_VERSION
    strategy:
      matrix:
        include:
#VERSIONS
          - name: bullseye
            variant: bullseye
          - name: slim-bullseye
            variant: bullseye/slim
          - name: bookworm
            variant: bookworm
          - name: slim-bookworm
            variant: bookworm/slim
          - name: trixie
            variant: trixie
          - name: slim-trixie
            variant: trixie/slim
          - name: alpine3.20
            variant: alpine3.20
          - name: alpine3.21
            variant: alpine3.21
          - name: alpine3.22
            variant: alpine3.22
          - name: windowsservercoreltsc2019-gnu
            variant: windows/servercoreltsc2019/gnu
          - name: windowsnanoserverltsc2019-gnu
            variant: windows/nanoserverltsc2019/gnu
          - name: windowsservercoreltsc2022-gnu
            variant: windows/servercoreltsc2022/gnu
          - name: windowsnanoserverltsc2022-gnu
            variant: windows/nanoserverltsc2022/gnu
          - name: windowsservercoreltsc2025-gnu
            variant: windows/servercoreltsc2025/gnu
          - name: windowsnanoserverltsc2025-gnu
            variant: windows/nanoserverltsc2025/gnu
          - name: windowsservercoreltsc2019-17763-msvc
            variant: windows/servercoreltsc2019/msvc
          - name: windowsservercoreltsc2022-20348-msvc
            variant: windows/servercoreltsc2022/msvc
          - name: windowsservercoreltsc2025-22000-msvc
            variant: windows/servercoreltsc2025/msvc
#VERSIONS
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v5
      - run: git clone https://github.com/docker-library/official-images.git ~/official-images
      - run: docker build -t rust:$RUST_VERSION-${{ matrix.name }} stable/${{ matrix.variant }}
      - run: ~/official-images/test/run.sh rust:$RUST_VERSION-${{ matrix.name }}
      - run: docker images
